### ISSUE TITLE
Get duration of a statement

### ISSUE THREAD

**Issue by mydnicq** [vitaly-t/pg-monitor#13]
I'm using this awesome module with massive.js. I'm wondering if it is possible to get a duration of a specific statement? Now I get event info displayed in this form:

```
14:59:07 connect(playground@playground)
14:59:07 SELECT COUNT(1) FROM "users"
WHERE TRUE LIMIT 1
14:59:07 disconnect(playground@playground)
14:59:07 connect(playground@playground)
14:59:07 SELECT * FROM "users"
WHERE "id" = 1 ORDER BY "id" LIMIT 10
14:59:07 disconnect(playground@playground)
14:59:07 connect(playground@playground)
14:59:07 SELECT * FROM "books"
WHERE "user_id" = 1 ORDER BY "id"
14:59:07 disconnect(playground@playground)
```

**Comment by vitaly-t** [comment]
By specific statement do you mean a specific query?

If so, then you can do it with most of the query methods on your side. For example, methods `any`, `manyOrNone`, `result` - all resolve with the array/object that has property `duration` on it.

pg-monitor however does not report such details.
