### ISSUE TITLE
Pass custom logger

### ISSUE THREAD

**Issue by arshad1tixsee** [vitaly-t/pg-monitor#14]
can i pass cutom logger we have customized bunyan logger and using it in all the application need to pass that logger to pg-monitor to log.info all the queries passed to pg promise

**Comment by vitaly-t** [comment]
Sure, why not? You can just set `info.display = false`, and that's it, it won't display anything on screen ;)

https://github.com/vitaly-t/pg-monitor#log

**Comment by arshad1tixsee** [comment]
sorry may be my question phrase is not right I need pg-monitor to print log on my logger when i make a file out of my logger i can see those as well currently pg-monitor logs are independent of my bunyan logger wrapper

**Comment by vitaly-t** [comment]
Ok, I see now...

`pg-monitor` is all about handling events from `pg-promise`, formatting messages and displaying them. From what you are telling me, you don't need any of that, which means you do not need `pg-nonitor` at all.

Instead, you should handle `pg-promise` events yourself, which is what `pg-monitor` does, and then output those events as you please.

**Comment by vitaly-t** [comment]
Alternatively, you can set up a dual system, if you want, as pg-monitor intelligently adds event handlers, it doesn't override them, unless you ask it to.

**Comment by arshad1tixsee** [comment]
ok I will reuse the code in pg-monitor and override print function thanks for your help

**Comment by vitaly-t** [comment]
More or less, though the whole `pg-monitor` code is a bit of an overkill for what you want. You won't need half of it ;)
