### ISSUE TITLE
can't seem to get output from pg-monitor

### ISSUE THREAD

**Issue by cpainterwakefield** [vitaly-t/pg-monitor#17]
Sorry, I'm a total newbie at node.js - any help you can give would be appreciated.
I'm using express with massive.js, and wanted to use pg-monitor.  I installed it and added these lines to app.js:

```
const monitor = require('pg-monitor');
monitor.attach({});
```
However, nothing appears on the console (or anywhere else that I can see) when I execute a query via massive.  I've tried a few different things, but no luck.  Is there a step I'm missing?

Thanks!

**Comment by vitaly-t** [comment]
You should follow [the massive documentation on this](https://github.com/dmfay/massive-js/blob/a429162c08b9c08a2029f54a43cb9171fa0ed6bd/docs/index.md#monitoring-queries), and if there is still an issue - raise a question there.

You are supposed to pass the `pg-promise` initialization options object into method `attach`, not an empty object.

**Comment by brandonros** [comment]
monitor.js:

```
const monitor = require('pg-monitor');

const options = {
	host: 'redacted',
	port: 5432,
	database: 'redacted',
	user: 'redacted'
	password: 'redacted'
}

monitor.attach(options); // attach to all events at once;
```

version 1.1.0 of pg-monitor inistalled

I am doing this and the node program just exits immediately with a status code of 0, no output.

**Comment by vitaly-t** [comment]
@brandonros you got this all wrong, see https://github.com/vitaly-t/pg-promise/blob/master/examples/monitor.js
