### ISSUE TITLE
Tiny issue stopping console.log output

### ISSUE THREAD

**Issue by bmershon** [vitaly-t/pg-monitor#2]
I've been using [TAPE](https://github.com/substack/tape) piped to Faucet for TAP testing and summarization. Console statements seem to interfere with the summarizer.

``` bash
node transaction-test.js | faucet
```

I used `monitor.log` to direct output to a log file:

``` js
monitor.log = function(msg, info){
    wstream.write(msg + "\n");
};
```

BUT, I couldn't find a way around commenting out the console.log statement in pg-monitor:

https://github.com/vitaly-t/pg-monitor/blob/master/lib/index.js#L335

**Comment by vitaly-t** [comment]
pg-monitor was designed to output all the events onto the screen, it is its whole purpose.

I added support for the `log` event later on as a feature. It didn't occur to me at that point that someone would want to log everything externally and not even use the nice-formatted screen output.

Such functionality would need to be added.

**Comment by vitaly-t** [comment]
Implemented in [v.0.3.5](https://github.com/vitaly-t/pg-monitor/releases/tag/v.0.3.5)
