### ISSUE TITLE
Display more than just the error message and query

### ISSUE THREAD

**Issue by xehpuk** [vitaly-t/pg-monitor#21]
Concretely, the error code would be nice.

**Comment by vitaly-t** [comment]
For that, use event [error](https://vitaly-t.github.io/pg-promise/global.html#event:error), and display anything you want.

```js
const initOptions = {
    error(err, e) {
        // display the error code, if it is available:
        if(err.code) {
            console.log('ERR-CODE:', err.code);
        }
    }
};
```

**Comment by xehpuk** [comment]
Yeah, that's what I do as a workaround. But I'd like to have it inside the output of `pg-monitor`, like:
```
error: {error.code} {error.message}
query: {query}
```

**Comment by vitaly-t** [comment]
> I'd like to have it inside the output of `pg-monitor`

You can add the code to the error message then:

```js
const options = {
    error(err, e) {
        if (err.code) {
            err.message = `${err.code} ${err.message}`;
        }
    }
};
```

**Comment by xehpuk** [comment]
Hacky, but an easy fix. Thanks!

**Comment by vitaly-t** [comment]
Yeah, a little, but safe enough :smile:
