### ISSUE TITLE
Docs say to pass in null/undefined when there are no options, but that does not work

### ISSUE THREAD

**Issue by clintonmedbery** [vitaly-t/pg-monitor#26]
> Optional array of event names to which to attach. Passing null/undefined will attach to all known events.

Yet when I do 
`monitor.attach(null);`
or 

I get:
> TypeError: Initialization object 'options' must be specified.

I think an explicit example with no options would be nice to see.

**Comment by vitaly-t** [comment]
`null` is for the `options`:

```js
monitor.attach(initOptions);
// the same as:
monitor.attach(initOptions, null);
```

You misunderstood the context of that parameter.

It will treat `null` in that case the same as handling all known events:

```js
monitor.attach(initOptions, ['connect', 'disconnect', 'query', 'task', 'transact', 'error']);
```
