### ISSUE TITLE
Disable Timestamp Support

### ISSUE THREAD

**Issue by dplewis** [vitaly-t/pg-monitor#31]
Thank you for this amazing library. I was trying to do a diff between two outputs and every line conflicted due to timestamps. I wanted to know if there was a way to disable the timestamp and possibly duration.

<img width="1311" alt="Screen Shot 2021-03-10 at 9 07 39 AM" src="https://user-images.githubusercontent.com/9830365/110650688-5f52f000-8180-11eb-905a-380370a717c6.png">

**Comment by vitaly-t** [comment]
Color output on the screen is not intended for running any kind of comparison, and so it is not modifiable.

For that purpose there is `log` event handler:

```js
monitor.setLog((msg, info) => {
    // msg = full message, without color
    // info = {event, time, colorText, text, display}

    // do what you want here, like writing into your log file.

    // you can suppress the on-screen output, with: info.display = false
});
```

See [event `log`](https://github.com/vitaly-t/pg-monitor#log).

b.t.w., [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) shows [full usage of the `log` event](https://github.com/vitaly-t/pg-promise-demo/blob/master/TypeScript/db/diagnostics.ts#L27) ;)

**Comment by dplewis** [comment]
Thanks I got it to work!
