### ISSUE TITLE
Typescript 2.0 typings required

### ISSUE THREAD

**Issue by dave-gray101** [vitaly-t/pg-monitor#9]
Similar to spex and pg-promise, I also need pg-monitor to include its typings via package.json.

I've created a [pull request](https://github.com/vitaly-t/pg-monitor/pull/8) to implement this feature.

**Comment by vitaly-t** [comment]
@dlee-nvisia thanks, I saw it, trying to make time to review it and merge,...will do later ;)

**Comment by dave-gray101** [comment]
@vitaly-t Thanks, I just realized I had never made a corresponding issue, so I wanted to make sure everything was tracked properly.

**Comment by vitaly-t** [comment]
Merged, will follow up there, no need for a separate issue ;)

**Comment by vitaly-t** [comment]
New version for TypeScript 2.0 has been published as 0.6.0 :wink:
